-- Event analytics tables (formerly ClickHouse). Conventions, kept from
-- ClickHouse so the ported queries keep their meaning:
--   * strings are NOT NULL DEFAULT '' (ClickHouse had no NULL strings);
--   * `properties` is jsonb holding the same flattened map ClickHouse stored
--     as Map(String, String): dotted keys (toDots), string values;
--   * timestamps are timestamptz(3) instants (ClickHouse DateTime64(3), UTC).
-- Ids are unique keys instead of ReplacingMergeTree/CollapsingMergeTree
-- versions, so no FINAL / sign arithmetic is needed when reading.

CREATE TABLE analytics.events (
  id uuid NOT NULL,
  project_id text NOT NULL,
  name text NOT NULL,
  sdk_name text NOT NULL DEFAULT '',
  sdk_version text NOT NULL DEFAULT '',
  device_id text NOT NULL DEFAULT '',
  -- Anonymous events carry the device id here.
  profile_id text NOT NULL DEFAULT '',
  session_id text NOT NULL DEFAULT '',
  groups text[] NOT NULL DEFAULT '{}',
  path text NOT NULL DEFAULT '',
  origin text NOT NULL DEFAULT '',
  referrer text NOT NULL DEFAULT '',
  referrer_name text NOT NULL DEFAULT '',
  referrer_type text NOT NULL DEFAULT '',
  revenue bigint NOT NULL DEFAULT 0,
  -- Milliseconds.
  duration bigint NOT NULL DEFAULT 0,
  properties jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz(3) NOT NULL,
  country text NOT NULL DEFAULT '',
  city text NOT NULL DEFAULT '',
  region text NOT NULL DEFAULT '',
  longitude real,
  latitude real,
  os text NOT NULL DEFAULT '',
  os_version text NOT NULL DEFAULT '',
  browser text NOT NULL DEFAULT '',
  browser_version text NOT NULL DEFAULT '',
  device text NOT NULL DEFAULT '',
  brand text NOT NULL DEFAULT '',
  model text NOT NULL DEFAULT '',
  imported_at timestamptz(3),
  -- Ingestion time (backdated events still get a real insert time).
  inserted_at timestamptz(3) NOT NULL DEFAULT now(),
  -- Insert order: the incremental backup/export cursor.
  seq bigint GENERATED BY DEFAULT AS IDENTITY,
  -- Also the idempotency key: a redelivered event is ON CONFLICT DO NOTHING.
  PRIMARY KEY (project_id, created_at, id)
);

CREATE INDEX events_name_idx ON analytics.events (project_id, name, created_at);
CREATE INDEX events_profile_idx ON analytics.events (project_id, profile_id, created_at);
CREATE INDEX events_session_idx ON analytics.events (project_id, session_id, created_at);
CREATE INDEX events_id_idx ON analytics.events (id);
CREATE INDEX events_seq_idx ON analytics.events (seq);

-- One row per session, kept current by the ingest consumer (upserts guarded
-- by `version`) and finalized by the session reaper.
CREATE TABLE analytics.sessions (
  id text NOT NULL,
  project_id text NOT NULL,
  profile_id text NOT NULL DEFAULT '',
  device_id text NOT NULL DEFAULT '',
  groups text[] NOT NULL DEFAULT '{}',
  created_at timestamptz(3) NOT NULL,
  ended_at timestamptz(3) NOT NULL,
  is_bounce boolean NOT NULL DEFAULT true,
  entry_origin text NOT NULL DEFAULT '',
  entry_path text NOT NULL DEFAULT '',
  exit_origin text NOT NULL DEFAULT '',
  exit_path text NOT NULL DEFAULT '',
  screen_view_count integer NOT NULL DEFAULT 0,
  revenue double precision NOT NULL DEFAULT 0,
  event_count integer NOT NULL DEFAULT 0,
  -- Milliseconds.
  duration bigint NOT NULL DEFAULT 0,
  country text NOT NULL DEFAULT '',
  region text NOT NULL DEFAULT '',
  city text NOT NULL DEFAULT '',
  longitude real,
  latitude real,
  device text NOT NULL DEFAULT '',
  brand text NOT NULL DEFAULT '',
  model text NOT NULL DEFAULT '',
  browser text NOT NULL DEFAULT '',
  browser_version text NOT NULL DEFAULT '',
  os text NOT NULL DEFAULT '',
  os_version text NOT NULL DEFAULT '',
  utm_medium text NOT NULL DEFAULT '',
  utm_source text NOT NULL DEFAULT '',
  utm_campaign text NOT NULL DEFAULT '',
  utm_content text NOT NULL DEFAULT '',
  utm_term text NOT NULL DEFAULT '',
  referrer text NOT NULL DEFAULT '',
  referrer_name text NOT NULL DEFAULT '',
  referrer_type text NOT NULL DEFAULT '',
  version bigint NOT NULL DEFAULT 1,
  PRIMARY KEY (project_id, id)
);

CREATE INDEX sessions_created_idx ON analytics.sessions (project_id, created_at);
CREATE INDEX sessions_profile_idx ON analytics.sessions (project_id, profile_id, created_at);

-- Latest state per profile (ReplacingMergeTree(last_seen_at) before).
CREATE TABLE analytics.profiles (
  project_id text NOT NULL,
  id text NOT NULL,
  is_external boolean NOT NULL DEFAULT false,
  first_name text NOT NULL DEFAULT '',
  last_name text NOT NULL DEFAULT '',
  email text NOT NULL DEFAULT '',
  avatar text NOT NULL DEFAULT '',
  properties jsonb NOT NULL DEFAULT '{}',
  groups text[] NOT NULL DEFAULT '{}',
  created_at timestamptz(3) NOT NULL DEFAULT now(),
  last_seen_at timestamptz(3) NOT NULL DEFAULT now(),
  PRIMARY KEY (project_id, id)
);

CREATE INDEX profiles_created_idx ON analytics.profiles (project_id, created_at);
CREATE INDEX profiles_last_seen_idx ON analytics.profiles (project_id, last_seen_at);

-- Latest state per group (ReplacingMergeTree(version, deleted) before;
-- deletes are real deletes now). `version` is the write time in ms and is
-- read back as updatedAt.
CREATE TABLE analytics.groups (
  project_id text NOT NULL,
  id text NOT NULL,
  type text NOT NULL DEFAULT '',
  name text NOT NULL DEFAULT '',
  properties jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz(3) NOT NULL DEFAULT now(),
  version bigint NOT NULL,
  PRIMARY KEY (project_id, id)
);

CREATE INDEX groups_type_idx ON analytics.groups (project_id, type);

CREATE TABLE analytics.events_bots (
  id uuid NOT NULL,
  project_id text NOT NULL,
  name text NOT NULL DEFAULT '',
  type text NOT NULL DEFAULT '',
  path text NOT NULL DEFAULT '',
  created_at timestamptz(3) NOT NULL,
  PRIMARY KEY (project_id, created_at, id)
);

-- rrweb chunks (a JSON array of events, typically 10–100 KB, at most 2 MB)
-- written straight from /track. Kept 30 days by the cleanup cron. A chunk
-- the SDK sends twice is stored once.
CREATE TABLE analytics.session_replay_chunks (
  project_id text NOT NULL,
  session_id text NOT NULL,
  started_at timestamptz(3) NOT NULL,
  chunk_index integer NOT NULL,
  ended_at timestamptz(3) NOT NULL,
  events_count integer NOT NULL DEFAULT 0,
  is_full_snapshot boolean NOT NULL DEFAULT false,
  payload text COMPRESSION lz4 NOT NULL,
  inserted_at timestamptz(3) NOT NULL DEFAULT now(),
  PRIMARY KEY (project_id, session_id, started_at, chunk_index)
);

CREATE INDEX session_replay_chunks_started_idx
  ON analytics.session_replay_chunks (started_at);
